#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Miyako Jones' Portfolio
url: 'http://www.miyako.io'
baseurl: '' #change it according to your repository name
description: 4 years of combined experience with website development and software engineering. Organized, responsible, hard-working, a team player, and a self-starter.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
open_url: false
