baseURL = "https://miyakoj.github.io"
languageCode = "en-us"
title = "Miyako Jones' Portfolio"
theme = "default"
enableGitInfo = true
enableRobotsTXT = true

[params.icons]
    word = "fa-file-word"
    pdf = "fa-file-pdf"
    doc = "fa-file"
    video = "fa-video"
    website = "fa-globe"
    image = "fa-image"